// Inline the cr-sqlite WASM as base64 so the built page needs no network fetch — it runs straight
// from file://. Emitted as plain .js (not .ts) on purpose: a ~2.3 MB string literal is pointless
// work for tsc, so src/engine/wasm.d.ts describes it instead. Written next to that declaration so
// the `./wasm.js` import in db.ts resolves to the right types.
//
// Generated, not source: gitignored, and rewritten by every build and test run.
import { readFileSync, writeFileSync } from 'fs';

const SRC = './node_modules/@vlcn.io/wa-sqlite/dist/crsqlite.wasm';
const wasm = readFileSync(new URL(SRC, import.meta.url));

writeFileSync(
  new URL('./src/engine/wasm.js', import.meta.url),
  `// AUTO-GENERATED by embed.mjs — do not edit. Source: ${SRC}\n` +
    `export const WASM_B64 = ${JSON.stringify(wasm.toString('base64'))};\n`,
);

console.log(`embedded crsqlite.wasm: ${(wasm.length / 1e6).toFixed(2)} MB raw`);
